name: 'AI Inference'
description: Generate an AI response based on a provided prompt
author: 'GitHub'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'play-circle'
  color: red

# Define your inputs here.
inputs:
  prompt:
    description: Your input description here
    required: true
    default: ''

# Define your outputs here.
outputs:
  response:
    description: The response from the model

runs:
  using: node20
  main: dist/index.js
